/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

fun calculate(num1: Int, num2: Int, op: String): Int? {
    // return - when 문법을 사용하여 연산을 수행
    return when (op) {
        "+" -> num1 + num2
        "-" -> num1 - num2
        "*" -> num1 * num2
        "/" -> if (num2 != 0) num1 / num2 else null
        else -> null
    }
}

fun main() {
    print("첫 번째 숫자를 입력하세요: ")
    val input1 = readLine() // 사용자 입력을 readonly 변수에 저장
    // 입력값을 Int로 변환
    // 실패시 모두 null 처리
    val num1 = input1?.toIntOrNull()

    print("두 번째 숫자를 입력하세요: ")
    val input2 = readLine()
    val num2 = input2?.toIntOrNull()

    print("연산자를 입력하세요 (+, -, *, /): ")
    val op = readLine()

    // 입력값이 null이거나 숫자가 아닌 경우 처리
    if(num1 == null || num2 == null || op == null) {
        println("잘못된 입력입니다.")
        return
    }

    // calculate 함수를 호출하여 결과를 계산
    val result = calculate(num1, num2, op)
    if (result != null) {
        println("결과: $result")
    } else {
        println("잘못된 연산자입니다.")
    }
}
