/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    print("숫자를 입력하세요: ")
    val input = readLine() // 사용자 입력을 readonly 변수에 저장
    println("입력한 값: $input") // `$변수명` 형식으로 변수 출력
}
